
CREATE TABLE register
(
NAME VARCHAR2(20) NOT NULL,
PHONE_NUMBER NUMBER(10) NOT NULL,
EMAIL VARCHAR2(40) NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL,
DEPT_NAME VARCHAR2(20) NOT NULL,
EXPERIENCE NUMBER(38) NOT NULL
);
SELECT * FROM REGISTER;
CREATE TABLE ADMINREGISTARTION
(
ID NUMBER(10),
ADMIN_ID NUMBER(10),
ADMIN_NAME VARCHAR2(20),
EMAIL_ID VARCHAR2(55),
PHONE_NUMBER NUMBER(10),
PASSWORD VARCHAR2(20)
);
SELECT * FROM ADMINREGISTRATION;

CREATE TABLE
(
ID NUMBER(5),
ADMIN_ID NUMBER(5),
ADMIN_NAME VARCHAR2(20),
VACANCY_DEPT VARCHAR2(55),
VACANCY_DETAILS VARCHAR2(20),
JOB_LOCATION VARCHAR2(20),
COMPANY_NAME VARCHAR2(20),
PHONE_NO NUMBER(10)
);
SELECT * FROM ADMIN;
SELECT * FROM REGISTER;
SELECT * FROM ADMINREGISTRATION;
ALTER TABLE REGISTER ADD CONSTRAINT email_unique UNIQUE(EMAIL);
DESC REGISTER;
ALTER TABLE ADMINREGISTRATION ADD CONSTRAINT emailadmin_unique UNIQUE(EMAIL_ID);
DESC ADMINREGISTRATION;
commit;
select * from admin;